### ISSUE TITLE
Console ERROR

### ISSUE THREAD

**Issue by nestor50** [lukeleppan/better-word-count#67]
Hello, while checking the console I saw this error about better word count:
`app.js:1 TypeError: Cannot read properties of null (reading 'view')
    at BetterWordCount.giveEditorPlugin (plugin:better-word-count:7820:29)
    at eval (plugin:better-word-count:7801:18)
    at t.<anonymous> (app.js:1:1778730)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)`
Any hints about what's going on? should I fix it? Any help appreciated...

**Comment by mgmeyers** [comment]
This should be fixed in v0.10.0
